import { expect } from "chai";
import { customerModel } from "../models/customerModel.mjs";

describe("customer testing", () => {
    it("Should create a customer", () => {
        //testExample generated by AI => ChatGPT
        const customer = customerModel(
            "John",
            "Doe",
            "john.doe@example.com",
            "+123456789",
            "123 Main St"
        )

        expect(customer).to.have.property("id");
        expect(customer.firstName).to.equal("John");
        expect(customer.lastName).to.equal("Doe");
        expect(customer.email).to.equal("john.doe@example.com");
        expect(customer.phone).to.equal("+123456789");
        expect(customer.address).to.equal("123 Main St");
    })


})