import { Button, Input } from "@nextui-org/react";
import Head from "next/head";

export default function Login() {
    return (
      <>
        <Head>
          <title>Webprojekt DHBW</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <main>
            <div className="login">
              <h1 className="text">Log In</h1>
            <Input label="Nutzername" placeholder="Nutzername eingeben" type="text" className="input"/>
            <Input label="Passwort" placeholder="Passwort eingeben" type="password" className="input"/>
            <Button className="button">Einloggen</Button>
            </div>
          </main>
      </>
    );
  }